version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=series_user
      - DB_PASSWORD=series_pass
      - DB_NAME=series_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=series_user
      - POSTGRES_PASSWORD=series_pass
      - POSTGRES_DB=series_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "5432:5432"
volumes:
  db_data: